<h1><center>CMPE 462 - Project 2<br>Implementing an SVM Classifier<br>Due: May 18, 2020, 23:59</center></h1>

* **Student ID1:** 2016400249
* **Student ID2:** 2014400063
* **Student ID3:** 2009400165

## Overview

In this project, you are going to implement SVM. For this purpose, a data set (data.mat) is given to you. You can load the mat dataset into Python using the function `loadmat` in `Scipy.io`. When you load the data, you will obtain a dictionary object, where `X` stores the data matrix and `Y` stores the labels. You can use the first 150 samples for training and the rest for testing. In this project, you will use the software package [`LIBSVM`](http://www.csie.ntu.edu.tw/~cjlin/libsvm/) to implement SVM. Note that `LIBSVM` has a [`Python interface`](https://github.com/cjlin1/libsvm/tree/master/python), so you can call the SVM functions in Python. 

In [1]:
import scipy.io
import numpy as np

#loading the data
dataset = scipy.io.loadmat('data.mat')

#converting data matrix X and labels Y into numpy arrays
data_matrix =  np.array(dataset['X'])
data_labels = np.array(dataset['Y']).flatten()

#dividing data as 150 samples for training and the rest for the test 
training_set_x,test_set_x = data_matrix[:150], data_matrix[150:]
training_set_labels, test_set_labels = data_labels[:150],data_labels[150:]


## Task 1 - 30 pts

Train a hard margin linear SVM and report both train and test classification accuracy.

In [2]:
import sys
#importing the library path to the system
sys.path.append('./libsvm-3.24/python')

In [3]:
import scipy
from svmutil import *

# We need a very high C value to approximate hard margine SVM.
# Training accuracy is not 100% because the data is not linearly seperable.
# We see that this actually is the solution with the optimal margin because
# test accuracy does not change with C is increasing.

hardMarginSvm = svm_train(training_set_labels,training_set_x, '-t 0 -c 420420420420')

p_label_train, p_acc_train, p_val_train = svm_predict(training_set_labels,training_set_x, hardMarginSvm)
p_label_test, p_acc_test, p_val_test = svm_predict(test_set_labels, test_set_x, hardMarginSvm)

Accuracy = 74.6667% (112/150) (classification)
Accuracy = 77.5% (93/120) (classification)


## Task 2 - 40 pts

Train soft margin SVM for different values of the parameter $C$, and with different kernel functions. Systematically report your results. For instance, report the performances of different kernels for a fixed $C$, then report the performance for different $C$ values for a fixed kernel, and so on.

In [4]:
# Experiments class is used for training soft margin svm with different  values of the parameter C 
# and with different kernel functions.
class Experiments:
    # Initializing training,test sets and its labels and also candidate values
    def __init__(self, training_set_x, training_set_labels, test_set_labels, test_set_x,c_parameters,candidate_kernels):
            self.training_set_x = training_set_x
            self.training_set_labels =  training_set_labels
            self.test_set_labels = test_set_labels
            self.test_set_x = test_set_x
            self.c_parameters = c_parameters
            self.candidate_kernels = candidate_kernels
            self.allResults = {}
            self.testAccuracies=np.array([0.0]*(len(c_parameters)*len(candidate_kernels)))
            self.testAccuracies=self.testAccuracies.reshape((len(c_parameters),len(candidate_kernels)))
            self.trainAccuracies=np.array([0.0]*(len(c_parameters)*len(candidate_kernels)))
            self.trainAccuracies=self.trainAccuracies.reshape((len(c_parameters),len(candidate_kernels)))
    
    #training svm with a given parameter specified in trainWithDifferentSetups fuction 
    def trainSvm(self, k_index,c_index):
        parameter = '-t ' + str(self.candidate_kernels[k_index]) + ' -c ' + str(self.c_parameters[c_index])
        svm = svm_train(self.training_set_labels,training_set_x, parameter)
        p_label_train, p_acc_train, p_val_train = svm_predict(self.training_set_labels,self.training_set_x, svm)
        p_label_test, p_acc_test, p_val_test = svm_predict(self.test_set_labels, self.test_set_x, svm)
        
        #appeding results of the tested svm
        self.allResults[parameter] = {'training': (p_label_train, p_acc_train, p_val_train),'test' : (p_label_test, p_acc_test, p_val_test)}
        self.testAccuracies[c_index,k_index]=p_acc_test[0]
        self.trainAccuracies[c_index,k_index]=p_acc_train[0]
        
    #training with different different  values of the parameter C and with different kernel functions.
    def trainWithDifferentSetups(self):
        for k_index in range(0,len(self.candidate_kernels)):
            for c_index in range(0,len(self.c_parameters)):
                self.trainSvm(k_index,c_index )

c_parameters = [0.05,0.5,5,50,500]
candidate_kernels = [0,1,2,3]
experiments =  Experiments(training_set_x, training_set_labels, test_set_labels, test_set_x,c_parameters,candidate_kernels)
experiments.trainWithDifferentSetups()
print(experiments.trainAccuracies)
print(experiments.testAccuracies)

Accuracy = 84.6667% (127/150) (classification)
Accuracy = 84.1667% (101/120) (classification)
Accuracy = 86.6667% (130/150) (classification)
Accuracy = 85% (102/120) (classification)
Accuracy = 88.6667% (133/150) (classification)
Accuracy = 81.6667% (98/120) (classification)
Accuracy = 88.6667% (133/150) (classification)
Accuracy = 81.6667% (98/120) (classification)
Accuracy = 90% (135/150) (classification)
Accuracy = 81.6667% (98/120) (classification)
Accuracy = 53.3333% (80/150) (classification)
Accuracy = 58.3333% (70/120) (classification)
Accuracy = 84.6667% (127/150) (classification)
Accuracy = 79.1667% (95/120) (classification)
Accuracy = 91.3333% (137/150) (classification)
Accuracy = 80.8333% (97/120) (classification)
Accuracy = 97.3333% (146/150) (classification)
Accuracy = 80% (96/120) (classification)
Accuracy = 100% (150/150) (classification)
Accuracy = 75% (90/120) (classification)
Accuracy = 76.6667% (115/150) (classification)
Accuracy = 77.5% (93/120) (classification)
Acc

## Task 3 - 15 pts

Please report how the number of support vectors changes as the value of $C$ increases (while all other parameters remain the same). Discuss whether your observations match the theory.

In [5]:
#observing the number of support vectors as the parameter C increases
for c in range(1,20,1):
    params="-t 0 -c "+str(c)
    model = svm_train(training_set_labels,training_set_x, params)
    print("C:"+str(c)+"\t # of support vectors:"+str(len(model.get_SV())))


C:1	 # of support vectors:58
C:2	 # of support vectors:56
C:3	 # of support vectors:55
C:4	 # of support vectors:54
C:5	 # of support vectors:54
C:6	 # of support vectors:53
C:7	 # of support vectors:52
C:8	 # of support vectors:52
C:9	 # of support vectors:50
C:10	 # of support vectors:51
C:11	 # of support vectors:51
C:12	 # of support vectors:51
C:13	 # of support vectors:51
C:14	 # of support vectors:50
C:15	 # of support vectors:50
C:16	 # of support vectors:50
C:17	 # of support vectors:50
C:18	 # of support vectors:50
C:19	 # of support vectors:50


As C increases, the machine tolerates less error, which results in a narrower margin. The number of vectors in the margin understandably decreases.

## Task 4 - 15 pts

Please investigate the changes in the hyperplane when you remove one of the support vectors, vs., one data point that is not a support vector.

In [6]:
# Get support vectors as numpy arrays
# LibSVM returns a dictionary with feature indices as keys
# Moreover, this dictionary doesn't include feature indices
# for feature that are 0, therefore we can not use a one liner
# like sv=[model.get_SV()[i+1] for i in range(0,13)]
def get_reshape_SV(m):
    tempSupVecs=m.get_SV()
    d=len(training_set_x[0])
    supVecs=np.array([0.0]*(len(tempSupVecs)*d))
    supVecs=supVecs.reshape((len(tempSupVecs),d))

    for v in range(0,len(tempSupVecs)):
        for i in range(0,d):
            if i+1 in tempSupVecs[v].keys():
                supVecs[v][i]=tempSupVecs[v][i+1]
            else:
                supVecs[v][i]=0
    return supVecs

#function getWeightsAndBias takes SVM modela and returns the weights of the support vectors and bias of the model
def getWeightsAndBias(model):
    SVs=get_reshape_SV(model)
    SVcoef = np.array([coef[0] for coef in model.get_sv_coef() ])   
    weights = np.matmul(SVs.T,SVcoef)
    bias = -model.rho[0]
    return weights,bias



#training the base model
params= "-t 0 -c " + str(c)
model_base = svm_train(training_set_labels,training_set_x, params)


#get the support vectos and rearrange the support vector array for further use
SVs_base=get_reshape_SV(model_base)
# Get index of the first support vector
SV0=SVs_base[0]
SV_index=-1
nonSV_index=-1
for i,dp in enumerate(training_set_x):
    if np.array_equal(np.array(dp),SV0):
        SV_index=i
        
# Get index of the first non support vector data point 
cont=True
for ix,dp in enumerate(training_set_x):
    if cont:
        for isv,sv in enumerate(SVs_base):
            if not np.array_equal(np.array(dp),SVs_base[isv]):
                nonSV_index=ix
                cont=False
                
#weights and bias values of the base model
weights_base,bias_base  = getWeightsAndBias(model_base)

#training model with removed support vector
training_set_x_removedSV = np.delete(training_set_x,SV_index,axis=0)
training_set_labels_removedSV = np.delete(training_set_labels, SV_index)
model_removedSV = svm_train(training_set_labels_removedSV,training_set_x_removedSV, params)

#weights and bias values of the base model
weights_removedSV ,bias_removedSV  = getWeightsAndBias(model_removedSV)

#training model with removed support vector
training_set_x_removedNonSV = np.delete(training_set_x, nonSV_index,axis=0)
training_set_labels_removedNonSV = np.delete(training_set_labels, nonSV_index)
model_removedNonSV = svm_train(training_set_labels_removedNonSV,training_set_x_removedNonSV, params)

#weights and bias values of the base model
weights_removedNonSV ,bias_removedNonSV  = getWeightsAndBias(model_removedNonSV)
print("##################################")
print(weights_base,bias_base)
print("##################################")
print(weights_removedSV ,bias_removedSV )
print("##################################")
print(weights_removedNonSV ,bias_removedNonSV)

##################################
[-1.30888701  0.52571551  1.3470139   1.37874173  1.6273681   0.16133491
  0.13203498 -1.8521204  -0.02562698 -0.0762774   0.06906356  2.72479396
  0.44811908] 2.3785383593196174
##################################
[-1.32983847  0.50137912  1.51487358  1.32368342  1.22296991  0.09252357
  0.23434143 -1.66513531 -0.08056412  0.29650759  0.01183793  2.98157394
  0.42209016] 2.426370193620015
##################################
[-1.30888701  0.52571551  1.3470139   1.37874173  1.6273681   0.16133491
  0.13203498 -1.8521204  -0.02562698 -0.0762774   0.06906356  2.72479396
  0.44811908] 2.3785383593196174


### Bonus Task - 10 pts

Use Python and [CVXOPT](http://cvxopt.org) QP solver to implement the hard margin SVM. 

In [7]:
from cvxopt import matrix
from cvxopt import matrix as cvxopt_matrix
from cvxopt import solvers as cvxopt_solvers

#function QPSolver takes train data and its labels and applies the cvxopt library to solve qp problem
def QPSolver(X,y):
    
    n, dim = X.shape
    Q = np.eye(dim)
    Q = np.insert(Q, 0, 0, axis=1)
    Q = np.insert(Q, 0, 0, axis=0)
    
    p = np.zeros(dim + 1 ).reshape(-1,1)
    
    A = y.reshape(-1,1) * np.insert(X, 0, 1, axis=1) * 1.
    
    c = (np.ones(n) * 1.).reshape(-1,1)
    P = cvxopt_matrix(Q)
    q = cvxopt_matrix(-p)
    G = cvxopt_matrix(-A)
    h = cvxopt_matrix(c)

    print(P)
    print(q)
    print(G)
    print(h)
    #Run qp solver for the primal problem
    sol_t = cvxopt_solvers.qp(P, q, G, h,kktsolver='ldl', options={'kktreg':1e-10})
    #get bias and weights
    w_t = np.array(sol_t['x'])
    print(w_t)

    
toy_train = np.array([[0,0],[2,2],[2,0],[3,0]])
toy_label = np.array([-1,-1,1,1])
QPSolver(toy_train,toy_label)
# We have correctly constructed the needed matrices and vectors according to the course slides for 
#the primal respresentation. However, the QP solver needs an additional constraint of type Ax=b, 
#which is not derived in class. We tried giving A=0 matrix and b=0 vector.
#This resulted in an error saying Rank(A) should not be 1. 
#There is no documentation on the restrictions on Rank(A). 
#Moreover, when we omit A and b, the solver returns wrong solutions and there is no 
#documentation on the default values of A and b. Therefore, we abandon this approach and instead 
#implement the dual representation, using this web page as a guide : 
#https://xavierbourretsicotte.github.io/SVM_implementation.html  

[ 0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  1.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  1.00e+00]

[-0.00e+00]
[-0.00e+00]
[-0.00e+00]

[ 1.00e+00 -0.00e+00 -0.00e+00]
[ 1.00e+00  2.00e+00  2.00e+00]
[-1.00e+00 -2.00e+00 -0.00e+00]
[-1.00e+00 -3.00e+00 -0.00e+00]

[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 1.00e+00]

     pcost       dcost       gap    pres   dres
 0:  3.2653e-01 -9.7959e-01  6e+00  1e+00  6e+00
 1:  7.5465e-03 -3.0317e-01  3e-01  2e-02  9e-02
 2:  7.8915e-06 -4.9791e-03  5e-03  1e-10  1e-11
 3:  7.9212e-10 -4.9790e-05  5e-05  1e-10  6e-13
 4:  7.9213e-14 -4.9790e-07  5e-07  1e-10  1e-14
 5:  7.9213e-18 -4.9790e-09  5e-09  1e-10  1e-16
Optimal solution found.
[[-4.41844496e-02]
 [ 2.23716118e-09]
 [-3.29205308e-09]]


In [8]:
#we take the website:https://xavierbourretsicotte.github.io/SVM_implementation.html
#to implement dual solution for the toy dataset and our training dataset
dim,n = toy_train.shape
toy_label_n = toy_label.reshape(-1,1) * 1.
toy_train_dash = toy_label_n * toy_train
H_t = np.matmul(toy_train_dash , toy_train_dash.T) * 1.

In [17]:
#converting (Q,p,A,c) (in class)  to (P,q,G,h,A,b) to implement the format of cvxopt library
P_t = cvxopt_matrix(H_t)
q_t = cvxopt_matrix(-np.ones((dim, 1)))
G_t = cvxopt_matrix(-np.eye(dim))
h_t = cvxopt_matrix(np.zeros(dim))
A_t = cvxopt_matrix(toy_label_n.reshape(1, -1))
b_t = cvxopt_matrix(np.zeros(1))

In [18]:
#Run cvxopt solver to solve qp problem
sol_t = cvxopt_solvers.qp(P_t, q_t, G_t, h_t, A_t, b_t)
#take the solution alphas
alphas = np.array(sol_t['x'])

     pcost       dcost       gap    pres   dres
 0: -8.1633e-01 -2.1224e+00  6e+00  2e+00  2e+00
 1: -8.5663e-01 -1.5796e+00  7e-01  2e-16  3e-16
 2: -9.9227e-01 -1.0195e+00  3e-02  2e-16  3e-16
 3: -9.9992e-01 -1.0002e+00  3e-04  2e-16  2e-16
 4: -1.0000e+00 -1.0000e+00  3e-06  2e-16  3e-16
 5: -1.0000e+00 -1.0000e+00  3e-08  2e-16  2e-16
Optimal solution found.


In [19]:
yalpha=(toy_label_n* alphas)
weights=np.matmul(yalpha.T,toy_train).reshape(toy_train.shape[1])
# indices of nonzero alpha values
indice_list = []
for i in range(0,len(alphas)):
    if alphas[i]>1e-4:
        indice_list.append(i)
indice_list = np.array(indice_list)
print(indice_list)
bias = toy_label_n[indice_list] - np.matmul(toy_train[indice_list], weights)

print('Alphas = ',alphas[alphas > 1e-4])
print('w = ', weights.flatten())
print('b = ', bias[0][0])

[0 1 2]
Alphas =  [0.5        0.50000001 1.        ]
w =  [ 1.00000001 -1.00000001]
b =  -1.0
